apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: order-db-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: order-db-config
data:
  POSTGRES_DB: "orders_db"
  POSTGRES_USER: "postgres"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-db
  template:
    metadata:
      labels:
        app: order-db
    spec:
      containers:
        - name: postgres
          image: postgres:15-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: order-db-config
                  key: POSTGRES_DB

            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: order-db-config
                  key: POSTGRES_USER

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: order-db-password

          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: order-postgres-storage
      volumes:
        - name: order-postgres-storage
          persistentVolumeClaim:
            claimName: order-db-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: order-db-service
spec:
  selector:
    app: order-db
  ports:
    - port: 5432
      targetPort: 5432