apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
stringData:
  jwt-secret-value: "c2VjcmV0LWtleS10aGlzLWlzLXZlcnmteWVyeS1sb25nLWJhc2U2NC1rZXk="
  user-db-password: "user_password"
  auth-db-password: "password"
  order-db-password: "order_password"
  mongo-root-password: "password"